import type { NextPage } from 'next';
import Head from 'next/head';
import Form from './layout/Form';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
        </section>
        <section>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Commodi, distinctio eum cum magnam similique consequatur, doloribus molestias et
            nemo necessitatibus blanditiis laboriosam? Voluptate, voluptatum esse. Mollitia reiciendis ut ullam accusamus.
          </p>
        </section>
        <section>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Commodi, distinctio eum cum magnam similique consequatur, doloribus molestias et
            nemo necessitatibus blanditiis laboriosam? Voluptate, voluptatum esse. Mollitia reiciendis ut ullam accusamus.
          </p>
        </section>
        <Form />
      </main>

      <footer>
        <span>foo</span>
      </footer>
    </div>
  );
};

export default Home;
